name: Daily Data Complete

on:
  schedule:
    - cron: "40 1 * * *"   
  workflow_dispatch:       

jobs:
  skill_trend:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run data complete
        run: |
          python analysis/data_complete.py