name: Keep Render Awake
on:
  schedule:
    - cron: "*/10 * * * *"  # 10分おき
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: |
          curl -s https://ai-job-dashboard-ztxo.onrender.com/health || true