name: Test All Secrets

on:
  schedule:
    - cron: "*/5 * * * *"  
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Show all secrets
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
        run: |
          echo "SUPABASE_URL: ${SUPABASE_URL}"
          echo "SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}"
          echo "SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}"
          echo "SERPAPI_KEY: ${SERPAPI_KEY}"
          echo "AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}"
          echo "AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY}"

          if [ -z "$AZURE_OPENAI_KEY" ]; then
            echo "AZURE_OPENAI_KEY is EMPTY!"
            exit 1
          else
            echo "AZURE_OPENAI_KEY is set (masked above)"
          fi