name: Daily Skill Trend Scoring

on:
  schedule:
    - cron: "35 1 * * *"   
  workflow_dispatch:       

jobs:
  skill_trend:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas supabase python-dotenv scikit-learn numpy

      - name: Run skill trend scoring
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: |
          python analysis/trend_score.py